dist: bionic
language: c

before_script:
  - export HOME=`pwd`
  - GITVER=$(git describe --tags || git rev-parse --short HEAD)
  - mkdir cache || true
  - cd cache
  - curl -LO https://sourceforge.net/projects/lazarus/files/Lazarus%20Linux%20amd64%20DEB/Lazarus%202.0.10/fpc-src_3.2.0-1_amd64.deb
  - curl -LO https://sourceforge.net/projects/lazarus/files/Lazarus%20Linux%20amd64%20DEB/Lazarus%202.0.10/fpc-laz_3.2.0-1_amd64.deb
  - curl -LO https://sourceforge.net/projects/lazarus/files/Lazarus%20Linux%20amd64%20DEB/Lazarus%202.0.10/lazarus-project_2.0.10-0_amd64.deb
  - sudo dpkg -i fpc-laz_3.2.0-1_amd64.deb
  - sudo dpkg -i fpc-src_3.2.0-1_amd64.deb
  - sudo dpkg -i lazarus-project_2.0.10-0_amd64.deb || true
  - sudo apt-get update
  - sudo apt-get install --no-install-recommends -y -f
  - cd /usr/share/fpcsrc/3.2.0
  - sudo make clean all OS_TARGET=win32 CPU_TARGET=i386
  - sudo make crossinstall OS_TARGET=win32 CPU_TARGET=i386 INSTALL_PREFIX=/usr
  - sudo ln -sf /usr/lib/fpc/3.2.0/ppcross386 /usr/bin/ppcross386
  - cd $HOME

after_script:
  - mkdir artifacts
  - mv Pray-release.exe artifacts/
  - cd artifacts
  - zip pray-ci-artifacts.zip Pray-release.exe
  - curl -T pray-ci-artifacts.zip https://filepush.co/upload/pray-ci-artifacts-$GITVER.zip && echo || true


jobs:
  include:
    - stage: Build
      name: Cross build Pray for win32
      script:
        - /usr/bin/lazbuild --os=win32 --cpu=i386 --bm=Release --compiler=/usr/bin/ppcross386 Pray.lpi
